# Generated by Django 5.2.1 on 2025-08-10 14:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='establishment_registration_date',
            field=models.DateField(default=api.models.today_date, verbose_name="Date d'enregistrement"),
        ),
    ]
