# Generated by Django 5.2.1 on 2026-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='dashboard_analytique',
            field=models.BooleanField(default=False, verbose_name='Dashboard_analytique'),
        ),
    ]
