# Generated by Django 5.2.1 on 2025-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_of_sale',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.pointofsale'),
        ),
    ]
