# Generated by Django 5.2.1 on 2026-04-11 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsale',
            name='accessibilite',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='affluence',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='agent_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='date_collecte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='digitalisation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='fiche_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='gps_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='grande_voie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='monthly_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CA mensuel'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CA annuel'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='visibilite',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
