# Generated by Django 5.2.1 on 2025-08-18 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone de vente')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant vendu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='purchases/', verbose_name='Photo')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'achat")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.mobilevendor', verbose_name='Vendeur ambulant')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
