# Generated by Django 5.2.1 on 2025-08-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='base',
            field=models.CharField(blank=True, max_length=100, verbose_name='Base'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pushcard_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de pushcard'),
        ),
    ]
