# Generated by Django 5.2.1 on 2025-07-24 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_points_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='establishment_address',
            field=models.TextField(default='Abidjan', verbose_name='Adresse établissement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishment_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email établissement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishment_name',
            field=models.CharField(default='Lanfia', max_length=200, verbose_name="Nom de l'établissement"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone établissement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishment_registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishment_type',
            field=models.CharField(default='Boutique', max_length=50, verbose_name="Type d'établissement"),
            preserve_default=False,
        ),
    ]
