# Generated by Django 5.2.1 on 2025-10-10 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sale_latitude_sale_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('ventes', 'Rapport des Ventes'), ('stocks', 'Rapport des Stocks'), ('commandes', 'Rapport des Commandes'), ('clients', 'Rapport des Clients'), ('fournisseurs', 'Rapport des Fournisseurs'), ('vendeurs', 'Rapport des Vendeurs Ambulants'), ('points_vente', 'Rapport des Points de Vente'), ('performance', 'Rapport de Performance')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('filters', models.JSONField(default=dict)),
                ('data', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('size', models.CharField(default='0 KB', max_length=50)),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('point_of_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pointofsale')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
