# Generated by Django 5.2.1 on 2025-07-26 15:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_establishment_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mobile_vendors/')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_conge', 'En congé'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('tricycle', 'Tricycle'), ('velo', 'Vélo'), ('pied', 'À pied'), ('autre', 'Autre')], default='moto', max_length=20)),
                ('vehicle_id', models.CharField(blank=True, max_length=50, null=True)),
                ('zones', models.JSONField(default=list)),
                ('performance', models.FloatField(default=0.0)),
                ('average_daily_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_vendors', to='api.pointofsale', verbose_name='Point de vente associé')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendeur ambulant',
                'verbose_name_plural': 'Vendeurs ambulants',
                'ordering': ['-created_at'],
                'unique_together': {('first_name', 'last_name', 'point_of_sale')},
            },
        ),
        migrations.CreateModel(
            name='VendorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('sale', 'Vente'), ('stock_replenishment', 'Réapprovisionnement'), ('incident', 'Incident'), ('other', 'Autre')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_activities', to='api.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.mobilevendor')),
            ],
            options={
                'verbose_name': 'Activité de vendeur',
                'verbose_name_plural': 'Activités des vendeurs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('days_worked', models.PositiveIntegerField(default=0)),
                ('distance_covered', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.mobilevendor')),
            ],
            options={
                'verbose_name': 'Performance de vendeur',
                'verbose_name_plural': 'Performances des vendeurs',
                'ordering': ['-month'],
                'unique_together': {('vendor', 'month')},
            },
        ),
    ]
