# Generated by Django 5.2.1 on 2025-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase_base_purchase_latitude_purchase_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de pushcard'),
        ),
    ]
