# Generated by Django 5.2.1 on 2025-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='brander',
            field=models.BooleanField(default=False, verbose_name='Est brandé'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='marque_brander',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Marque du brander'),
        ),
    ]
