# Generated by Django 5.2.1 on 2025-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pointofsale_brander_pointofsale_marque_brander'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='analytique',
            field=models.BooleanField(default=False, verbose_name='Analytiques'),
        ),
        migrations.AddField(
            model_name='role',
            name='commande',
            field=models.BooleanField(default=False, verbose_name='Commandes'),
        ),
        migrations.AddField(
            model_name='role',
            name='commerciaux',
            field=models.BooleanField(default=False, verbose_name='Commerciaux'),
        ),
        migrations.AddField(
            model_name='role',
            name='configuration',
            field=models.BooleanField(default=False, verbose_name='Configurations'),
        ),
        migrations.AddField(
            model_name='role',
            name='distributeurs',
            field=models.BooleanField(default=False, verbose_name='Distributeurs'),
        ),
        migrations.AddField(
            model_name='role',
            name='geolocalisation',
            field=models.BooleanField(default=False, verbose_name='Geolocalisations'),
        ),
        migrations.AddField(
            model_name='role',
            name='inventaire',
            field=models.BooleanField(default=False, verbose_name='Inventaire'),
        ),
        migrations.AddField(
            model_name='role',
            name='prospects',
            field=models.BooleanField(default=False, verbose_name='Prospects'),
        ),
        migrations.AddField(
            model_name='role',
            name='tableau',
            field=models.BooleanField(default=False, verbose_name='Tableau de bord'),
        ),
        migrations.AddField(
            model_name='role',
            name='utilisateur',
            field=models.BooleanField(default=False, verbose_name='Utilisateurs'),
        ),
    ]
