# Generated by Django 5.2.1 on 2025-11-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_role_analytique_role_commande_role_commerciaux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasespos', to='api.pointofsale')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespos', to='api.productvariant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_vendorspos', to='api.mobilevendor')),
                ('vendor_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespos', to='api.vendoractivity')),
            ],
            options={
                'db_table': 'salespos',
                'ordering': ['-created_at'],
            },
        ),
    ]
