# Generated by Django 5.2.1 on 2025-07-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pointofsale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
