# Generated by Django 5.2.1 on 2025-11-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_salepos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='branding_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
