# Generated by Django 5.2.1 on 2025-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_district_ville_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='positions',
            field=models.BooleanField(default=False, verbose_name='Positions'),
        ),
    ]
