# Generated by Django 5.2.1 on 2025-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sale_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoractivity',
            name='quantity_assignes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoractivity',
            name='quantity_sales',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
