# Generated by Django 5.2.1 on 2025-12-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_role_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='createcommande',
            field=models.BooleanField(default=False, verbose_name='Createcommande'),
        ),
        migrations.AddField(
            model_name='role',
            name='vuecommande',
            field=models.BooleanField(default=False, verbose_name='Vuecommande'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Type de pushcard'),
        ),
    ]
