# Generated by Django 5.2.1 on 2025-09-07 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vendoractivity_quantity_assignes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire/Créateur'),
        ),
    ]
