# Generated by Django 5.2.1 on 2025-12-28 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_role_createcommande_role_vuecommande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilevendor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
