# Generated by Django 5.2.1 on 2025-09-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_affecte',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendoractivity',
            name='quantity_assignes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendoractivity',
            name='quantity_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
