# Generated by Django 5.2.1 on 2025-09-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orderitem_quantity_affecte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vendor_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_activities', to='api.vendoractivity'),
        ),
    ]
